# Generated by Django 3.2.4 on 2021-06-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('oferta', models.BooleanField()),
                ('precio', models.PositiveIntegerField()),
            ],
        ),
    ]
